# Sentyr Configuration - Financial Services (PCI-DSS, SOX, GLBA)
#
# This configuration is optimized for financial institutions with:
# - PCI-DSS compliance for payment card data
# - SOX (Sarbanes-Oxley) compliance for financial reporting
# - GLBA (Gramm-Leach-Bliley Act) for customer financial information
# - Real-time fraud detection
# - Strict access controls and audit trails

---

# Google Workspace Configuration
google_workspace:
  service_account_file: "${GWS_SERVICE_ACCOUNT_FILE}"
  subject_email: "${GWS_SUBJECT_EMAIL}"
  domain: "financialcorp.com"
  
  # Multi-region support
  regions:
    - "us-east"
    - "us-west"
    - "eu-west"
  
  scopes:
    - "https://www.googleapis.com/auth/drive.readonly"
    - "https://www.googleapis.com/auth/admin.directory.user.readonly"
    - "https://www.googleapis.com/auth/gmail.readonly"
    - "https://www.googleapis.com/auth/admin.directory.group.readonly"
    - "https://www.googleapis.com/auth/admin.reports.audit.readonly"

# Scanning Configuration
scanning:
  files:
    enabled: true
    external_only: false  # Scan ALL files
    check_pii: true
    check_pci: true  # Payment card data
    check_sox: true  # Financial records
    batch_size: 50  # Smaller batches for security
    max_workers: 20  # High concurrency for large org
    
    # Real-time scanning
    real_time: true
    scan_on_create: true
    scan_on_modify: true
    scan_on_share: true
    
    # High-risk file types
    priority_extensions:
      - ".xlsx"  # Spreadsheets with financial data
      - ".csv"   # Data exports
      - ".pdf"   # Reports
      - ".docx"  # Contracts
    
  users:
    enabled: true
    inactive_days: 14  # Very strict for financial
    check_suspended: true
    check_mfa_enabled: true
    check_privileged_access: true
    
  gmail:
    enabled: true
    check_attachments: true
    check_body: true
    max_messages: 5000
    real_time_monitoring: true

# Financial Data Detection
pii_detection:
  enabled: true
  confidence_threshold: 0.5  # Lower threshold for financial
  
  patterns:
    # Payment card data (PCI-DSS)
    - type: "credit_card"
      enabled: true
      confidence: 0.95
      luhn_check: true  # Validate with Luhn algorithm
      
    - type: "cvv"
      enabled: true
      pattern: "(?:CVV|CVC|CSC)[:\\s-]?\\d{3,4}"
      confidence: 0.9
      
    - type: "card_expiry"
      enabled: true
      pattern: "(?:Exp|Expiry|Expires)[:\\s-]?\\d{2}/\\d{2,4}"
      confidence: 0.8
    
    # Bank account information
    - type: "bank_account"
      enabled: true
      confidence: 0.9
      
    - type: "routing_number"
      enabled: true
      pattern: "(?:Routing|ABA)[:\\s-]?\\d{9}"
      confidence: 0.9
      
    - type: "iban"
      enabled: true
      pattern: "[A-Z]{2}\\d{2}[A-Z0-9]{11,30}"
      confidence: 0.9
      
    - type: "swift_code"
      enabled: true
      pattern: "[A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?"
      confidence: 0.9
    
    # Investment account information
    - type: "account_number"
      enabled: true
      pattern: "(?:Account|Acct)[:\\s-]?#?\\d{8,17}"
      confidence: 0.8
      
    - type: "portfolio_id"
      enabled: true
      pattern: "(?:Portfolio|Port)[:\\s-]?ID[:\\s-]?[A-Z0-9]{8,12}"
      confidence: 0.8
    
    # Customer information (GLBA)
    - type: "ssn"
      enabled: true
      confidence: 0.95
      
    - type: "tax_id"
      enabled: true
      pattern: "(?:EIN|Tax ID)[:\\s-]?\\d{2}-\\d{7}"
      confidence: 0.9
      
    - type: "dob"
      enabled: true
      confidence: 0.8
      
    - type: "income"
      enabled: true
      pattern: "(?:Income|Salary|Revenue)[:\\s-]?\\$[\\d,]+(?:\\.\\d{2})?"
      confidence: 0.7
      
    - type: "net_worth"
      enabled: true
      pattern: "(?:Net Worth|Assets)[:\\s-]?\\$[\\d,]+(?:\\.\\d{2})?"
      confidence: 0.7
    
    # Financial records (SOX)
    - type: "financial_statement"
      enabled: true
      pattern: "(?:Balance Sheet|Income Statement|Cash Flow)"
      confidence: 0.8
      
    - type: "audit_report"
      enabled: true
      pattern: "(?:Audit Report|Auditor's Opinion)"
      confidence: 0.9
      
    - type: "internal_control"
      enabled: true
      pattern: "(?:Internal Control|ICFR|SOX Control)"
      confidence: 0.8
    
    # Trading information
    - type: "insider_trading"
      enabled: true
      pattern: "(?:Material Non-Public|MNPI|Inside Information)"
      confidence: 0.9
      
    - type: "trade_order"
      enabled: true
      pattern: "(?:Buy|Sell|Trade)[:\\s-]?\\d+[:\\s-]?(?:shares|contracts)"
      confidence: 0.7

# Policies (Financial Services)
policies:
  expiration:
    enabled: true
    default_days: 1  # Very short for financial data
    notify_before_hours: 4  # Hours, not days
    grace_period_hours: 2
    
    # No external sharing of sensitive data
    block_external_pci: true
    block_external_sox: true
    block_external_glba: true
    
  lifecycle:
    enabled: true
    offboard_inactive_users: true
    immediate_revocation: true  # No grace period
    transfer_files: true
    audit_all_actions: true
    
  access_control:
    enabled: true
    require_mfa: true
    require_vpn: true
    require_device_compliance: true
    ip_whitelist_only: true
    
    # Segregation of duties (SOX)
    segregation_of_duties:
      enabled: true
      roles:
        - name: "trader"
          cannot_access: ["compliance_reports", "audit_logs"]
          
        - name: "compliance"
          cannot_access: ["trading_systems"]
          read_only: true
          
        - name: "auditor"
          read_only: true
          audit_all_access: true
    
  data_classification:
    enabled: true
    auto_classify: true
    classifications:
      - name: "PCI"
        sensitivity: "critical"
        retention_years: 3
        encryption_required: true
        no_external_sharing: true
        
      - name: "SOX"
        sensitivity: "critical"
        retention_years: 7
        encryption_required: true
        audit_all_access: true
        
      - name: "GLBA"
        sensitivity: "critical"
        retention_years: 5
        encryption_required: true
        customer_consent_required: true
        
      - name: "Material Non-Public"
        sensitivity: "critical"
        retention_years: 7
        encryption_required: true
        restricted_access: true

# Integrations
integrations:
  email:
    enabled: true
    smtp_host: "smtp.financialcorp.com"
    smtp_port: 587
    smtp_user: "${SMTP_USER}"
    smtp_password: "${SMTP_PASSWORD}"
    smtp_tls: true
    from_address: "compliance@financialcorp.com"
    to_addresses:
      - "compliance@financialcorp.com"
      - "ciso@financialcorp.com"
      - "cfo@financialcorp.com"
      - "legal@financialcorp.com"
    
    templates:
      pci_alert: |
        Subject: [CRITICAL] Payment Card Data Detected - PCI-DSS Violation
        
        IMMEDIATE ACTION REQUIRED: Payment card data has been detected.
        
        File: {file_name}
        Owner: {owner_email}
        Card Types: {card_types}
        Shared With: {shared_with}
        Detection Time: {timestamp}
        
        PCI-DSS REQUIREMENTS:
        1. Immediately revoke external access
        2. Encrypt or delete card data
        3. Notify PCI compliance team
        4. Document incident for audit
        5. Review access logs
        
        This is a CRITICAL compliance matter.
        
        Incident ID: {incident_id}
  
  # SIEM integration (required)
  siem:
    enabled: true
    type: "splunk"
    endpoint: "${SIEM_ENDPOINT}"
    token: "${SIEM_TOKEN}"
    index: "financial-compliance"
    real_time: true
    
  # Fraud detection system
  fraud_detection:
    enabled: true
    endpoint: "${FRAUD_DETECTION_ENDPOINT}"
    api_key: "${FRAUD_DETECTION_API_KEY}"
    real_time_alerts: true
    
  # Regulatory reporting
  regulatory:
    enabled: true
    
    # SEC reporting
    sec:
      enabled: true
      endpoint: "${SEC_REPORTING_ENDPOINT}"
      
    # FINRA reporting
    finra:
      enabled: true
      endpoint: "${FINRA_REPORTING_ENDPOINT}"
      
    # FinCEN (suspicious activity)
    fincen:
      enabled: true
      endpoint: "${FINCEN_REPORTING_ENDPOINT}"

# Reporting
reporting:
  enabled: true
  format: "pdf"
  output_dir: "/secure/compliance-reports"
  encryption: true
  digital_signature: true
  
  schedule:
    real_time_alerts: true
    hourly_summary: true
    daily_detailed: true
    weekly_executive: true
    monthly_compliance: true
    quarterly_sox: true
    annual_audit: true
  
  recipients:
    - "compliance@financialcorp.com"
    - "ciso@financialcorp.com"
    - "cfo@financialcorp.com"
    - "audit-committee@financialcorp.com"

# Storage
storage:
  database_path: "/secure/financial-data/state.db"
  cache_dir: "/secure/financial-cache"
  
  # Encryption (PCI-DSS requirement)
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_file: "/secure/keys/db-encryption-key"
    rotate_keys_days: 30  # Monthly rotation
    hsm_integration: true  # Hardware Security Module
  
  # Retention requirements
  retention:
    scan_history_days: 2555  # 7 years (SOX)
    file_state_days: 2555
    audit_logs_days: 2555
    pci_data_days: 1095  # 3 years (PCI-DSS)
    cache_ttl_seconds: 300  # 5 minutes only

# Performance
performance:
  max_workers: 20
  batch_size: 50
  rate_limit_delay: 0.05  # Fast for real-time
  
  cache:
    enabled: true
    ttl_seconds: 300  # Short TTL
    max_size_mb: 2000
    encryption: true
  
  incremental:
    enabled: true
  
  # Real-time processing
  real_time:
    enabled: true
    max_latency_seconds: 5
    priority_queue: true

# Logging (Comprehensive for SOX)
logging:
  level: "DEBUG"
  format: "json"
  output: "/secure/logs/financial-audit.log"
  
  # Tamper-proof logging
  encryption: true
  digital_signature: true
  write_once: true  # WORM storage
  
  rotation:
    max_size_mb: 100
    max_files: 1000  # 7-year retention
    compress: true
    
  # Log everything for SOX
  events:
    - "all_file_access"
    - "all_data_modifications"
    - "all_permission_changes"
    - "all_user_actions"
    - "all_system_events"
    - "all_api_calls"

# Monitoring (Real-time)
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_port: 8080
  
  # Real-time dashboards
  dashboards:
    - "pci_compliance"
    - "sox_controls"
    - "glba_privacy"
    - "fraud_detection"
    - "insider_trading"
  
  # Critical alerts
  alerts:
    - name: "pci_data_detected"
      severity: "critical"
      response_time_minutes: 5
      channels: ["email", "siem", "pagerduty", "sms"]
      
    - name: "sox_control_failure"
      severity: "critical"
      response_time_minutes: 15
      channels: ["email", "siem", "pagerduty"]
      
    - name: "insider_trading_risk"
      severity: "critical"
      response_time_minutes: 5
      channels: ["email", "siem", "pagerduty", "legal"]
      
    - name: "unauthorized_access"
      severity: "critical"
      response_time_minutes: 5
      channels: ["email", "siem", "pagerduty"]

# Security (Maximum)
security:
  encryption:
    enabled: true
    tls_min_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
    mutual_tls: true
  
  access_controls:
    ip_whitelist:
      enabled: true
      allowed_ips:
        - "10.0.0.0/8"  # Corporate network only
      block_by_default: true
    
    vpn_required: true
    mfa_required: true
    device_compliance_required: true
    
  session:
    timeout_minutes: 10  # Very short
    require_reauth: true
    single_session_only: true
    
  audit:
    enabled: true
    log_all_access: true
    log_all_changes: true
    tamper_protection: true
    real_time_monitoring: true

# Compliance
compliance:
  enabled: true
  
  frameworks:
    pci_dss:
      enabled: true
      version: "4.0"
      requirements:
        - "1: Firewall Configuration"
        - "2: Vendor Defaults"
        - "3: Stored Cardholder Data"
        - "4: Encryption in Transit"
        - "5: Anti-Virus"
        - "6: Secure Systems"
        - "7: Access Control"
        - "8: Unique IDs"
        - "9: Physical Access"
        - "10: Logging and Monitoring"
        - "11: Security Testing"
        - "12: Information Security Policy"
      
    sox:
      enabled: true
      sections:
        - "302: Corporate Responsibility"
        - "404: Management Assessment"
        - "409: Real-Time Disclosures"
        - "802: Criminal Penalties"
      controls:
        - "ITGC: IT General Controls"
        - "ITAC: IT Application Controls"
        - "ICFR: Internal Control over Financial Reporting"
      
    glba:
      enabled: true
      requirements:
        - "Financial Privacy Rule"
        - "Safeguards Rule"
        - "Pretexting Protection"

# Workflows
workflows:
  # PCI incident response
  pci_incident:
    enabled: true
    immediate_containment: true
    notify_acquirer: true
    forensic_investigation: true
    
  # SOX control testing
  sox_testing:
    enabled: true
    frequency_days: 90
    document_results: true
    
  # Insider trading prevention
  insider_trading_prevention:
    enabled: true
    monitor_mnpi: true
    trading_blackout_enforcement: true
    pre_clearance_required: true

# Scheduled Scans
schedules:
  # Continuous scanning
  continuous_scan:
    enabled: true
    interval_minutes: 15
    command: "scan files --real-time --check-pci --check-sox"
  
  # Hourly compliance check
  hourly_compliance:
    enabled: true
    cron: "0 * * * *"
    command: "compliance check --all-frameworks"
  
  # Daily SOX control test
  daily_sox:
    enabled: true
    cron: "0 6 * * *"
    command: "compliance test-controls --framework sox"
  
  # Weekly audit
  weekly_audit:
    enabled: true
    cron: "0 8 * * 1"
    command: "audit generate --comprehensive"

---

# Compliance Checklist

# PCI-DSS:
# [x] Requirement 1-12 implemented
# [x] Quarterly vulnerability scans
# [x] Annual penetration testing
# [x] Quarterly compliance reports

# SOX:
# [x] Section 302, 404, 409, 802 controls
# [x] ITGC and ITAC controls
# [x] Quarterly control testing
# [x] Annual audit

# GLBA:
# [x] Privacy notices
# [x] Safeguards program
# [x] Pretexting protection
# [x] Annual privacy training

---

# Estimated Costs

# For 1,000 users, 500,000 files:
# - API calls: 500,000/day
# - Storage: 50 GB (7-year retention)
# - Compute: 16 cores, 32 GB RAM
# - HSM: $5,000/month
# - SIEM: $10,000/month

---

# Support Contacts

# Compliance: compliance@financialcorp.com
# CISO: ciso@financialcorp.com
# Legal: legal@financialcorp.com
# Audit: audit@financialcorp.com

