# Sentyr Configuration - Healthcare (HIPAA Compliant)
#
# This configuration is optimized for healthcare organizations with:
# - HIPAA compliance requirements
# - PHI (Protected Health Information) detection
# - Strict access controls
# - Comprehensive audit logging
# - 7-year data retention
# - Encryption at rest and in transit

---

# Google Workspace Configuration
google_workspace:
  service_account_file: "${GWS_SERVICE_ACCOUNT_FILE}"
  subject_email: "${GWS_SUBJECT_EMAIL}"
  domain: "healthcare.org"
  
  # HIPAA-compliant scopes
  scopes:
    - "https://www.googleapis.com/auth/drive.readonly"
    - "https://www.googleapis.com/auth/admin.directory.user.readonly"
    - "https://www.googleapis.com/auth/gmail.readonly"
    - "https://www.googleapis.com/auth/admin.directory.group.readonly"

# Scanning Configuration
scanning:
  files:
    enabled: true
    external_only: false  # Scan ALL files for HIPAA
    check_pii: true
    check_phi: true  # Healthcare-specific
    batch_size: 100
    max_workers: 10
    
    # File type restrictions
    allowed_extensions:
      - ".pdf"
      - ".docx"
      - ".xlsx"
      - ".txt"
    
    # Scan frequency
    full_scan_frequency: "daily"
    incremental_scan: true
    
  users:
    enabled: true
    inactive_days: 30  # Stricter for healthcare
    check_suspended: true
    check_mfa_enabled: true  # HIPAA requirement
    
  gmail:
    enabled: true
    check_attachments: true
    check_body: true
    max_messages: 1000
    phi_detection: true

# PHI/PII Detection (HIPAA-specific)
pii_detection:
  enabled: true
  confidence_threshold: 0.6  # Lower threshold for healthcare
  
  # Healthcare-specific patterns
  patterns:
    # Patient identifiers
    - type: "medical_record_number"
      enabled: true
      pattern: "MRN[:\\s-]?\\d{6,10}"
      confidence: 0.9
      
    - type: "patient_id"
      enabled: true
      pattern: "(?:Patient|PT)[:\\s-]?ID[:\\s-]?\\d{6,10}"
      confidence: 0.9
    
    # Medical identifiers
    - type: "medicare_number"
      enabled: true
      confidence: 0.9
      
    - type: "medicaid_number"
      enabled: true
      confidence: 0.9
      
    - type: "health_plan_number"
      enabled: true
      pattern: "(?:Health Plan|Insurance)[:\\s-]?#?\\d{8,12}"
      confidence: 0.8
    
    # Provider identifiers
    - type: "npi"
      enabled: true
      confidence: 0.9
      
    - type: "dea_number"
      enabled: true
      confidence: 0.9
    
    # Standard PII
    - type: "ssn"
      enabled: true
      confidence: 0.9
      
    - type: "dob"
      enabled: true
      confidence: 0.8
      
    - type: "phone"
      enabled: true
      confidence: 0.7
      
    - type: "email"
      enabled: true
      confidence: 0.7
      
    - type: "address"
      enabled: true
      confidence: 0.7
    
    # Biometric identifiers
    - type: "fingerprint_id"
      enabled: true
      pattern: "(?:Fingerprint|FP)[:\\s-]?ID[:\\s-]?[A-Z0-9]{10,20}"
      confidence: 0.9
    
    # Medical information
    - type: "diagnosis_code"
      enabled: true
      pattern: "(?:ICD-10|ICD10)[:\\s-]?[A-Z]\\d{2}\\.?\\d{0,4}"
      confidence: 0.8
      
    - type: "prescription"
      enabled: true
      pattern: "(?:Rx|Prescription)[:\\s-]?#?\\d{8,12}"
      confidence: 0.8

# Policies (HIPAA-compliant)
policies:
  expiration:
    enabled: true
    default_days: 7  # Very short for PHI
    notify_before_days: 3
    grace_period_days: 1
    
    # No external sharing of PHI
    block_external_phi: true
    
  lifecycle:
    enabled: true
    offboard_inactive_users: true
    transfer_files: true
    suspend_account: true
    revoke_access: true
    
  access_control:
    enabled: true
    require_mfa: true
    require_vpn: true
    ip_whitelist_only: true
    
  data_classification:
    enabled: true
    auto_classify: true
    classifications:
      - name: "PHI"
        sensitivity: "critical"
        retention_years: 7
        encryption_required: true
        
      - name: "PII"
        sensitivity: "high"
        retention_years: 7
        encryption_required: true
        
      - name: "Confidential"
        sensitivity: "medium"
        retention_years: 3
        encryption_required: true

# Integrations
integrations:
  email:
    enabled: true
    smtp_host: "smtp.healthcare.org"
    smtp_port: 587
    smtp_user: "${SMTP_USER}"
    smtp_password: "${SMTP_PASSWORD}"
    smtp_tls: true
    from_address: "hipaa-compliance@healthcare.org"
    to_addresses:
      - "compliance@healthcare.org"
      - "security@healthcare.org"
      - "privacy-officer@healthcare.org"
    
    # HIPAA-compliant email templates
    templates:
      phi_alert: |
        Subject: [CRITICAL] PHI Detected in File - Immediate Action Required
        
        HIPAA ALERT: Protected Health Information (PHI) has been detected.
        
        File: {file_name}
        Owner: {owner_email}
        PHI Types: {phi_types}
        Shared With: {shared_with}
        Detection Time: {timestamp}
        
        IMMEDIATE ACTIONS REQUIRED:
        1. Review file access permissions
        2. Verify Business Associate Agreements (BAAs)
        3. Document in HIPAA audit log
        4. Notify Privacy Officer if external sharing detected
        
        This is a HIPAA compliance matter. Do not ignore.
        
        Incident ID: {incident_id}
  
  # SIEM integration (required for HIPAA)
  siem:
    enabled: true
    type: "splunk"
    endpoint: "${SIEM_ENDPOINT}"
    token: "${SIEM_TOKEN}"
    index: "hipaa-compliance"
    
  # Webhook for incident response
  webhook:
    enabled: true
    url: "${INCIDENT_RESPONSE_WEBHOOK}"
    events:
      - "phi_detected"
      - "unauthorized_access"
      - "policy_violation"
      - "external_share_created"

# Reporting (HIPAA-compliant)
reporting:
  enabled: true
  format: "pdf"  # Secure format
  output_dir: "/secure/hipaa-reports"
  encryption: true
  
  # HIPAA-required reports
  schedule:
    daily_phi_summary: true
    weekly_access_report: true
    monthly_compliance_report: true
    quarterly_risk_assessment: true
    annual_hipaa_audit: true
  
  recipients:
    - "compliance@healthcare.org"
    - "privacy-officer@healthcare.org"
    - "ciso@healthcare.org"

# Storage (HIPAA-compliant)
storage:
  database_path: "/secure/hipaa-data/state.db"
  cache_dir: "/secure/hipaa-cache"
  
  # Encryption at rest (REQUIRED)
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_file: "/secure/keys/db-encryption-key"
    rotate_keys_days: 90
  
  # HIPAA retention requirements
  retention:
    scan_history_days: 2555  # 7 years
    file_state_days: 2555
    audit_logs_days: 2555
    phi_detections_days: 2555
    cache_ttl_seconds: 1800  # 30 minutes

# Performance
performance:
  max_workers: 10
  batch_size: 100
  rate_limit_delay: 0.1
  
  cache:
    enabled: true
    ttl_seconds: 1800
    max_size_mb: 500
    encryption: true
  
  incremental:
    enabled: true

# Logging (HIPAA audit trail)
logging:
  level: "DEBUG"  # Comprehensive logging for HIPAA
  format: "json"
  output: "/secure/logs/hipaa-audit.log"
  
  # Encrypted logs
  encryption: true
  
  # Log rotation with retention
  rotation:
    max_size_mb: 100
    max_files: 100  # Keep many files for 7-year retention
    compress: true
    
  # Log all HIPAA-relevant events
  events:
    - "file_access"
    - "phi_detection"
    - "user_authentication"
    - "permission_change"
    - "policy_violation"
    - "external_share"
    - "data_export"
    - "configuration_change"

# Monitoring (HIPAA-required)
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_port: 8080
  
  # Real-time alerts
  alerts:
    - name: "phi_detected"
      severity: "critical"
      channels: ["email", "siem", "pagerduty"]
      
    - name: "unauthorized_access"
      severity: "critical"
      channels: ["email", "siem", "pagerduty"]
      
    - name: "external_share_phi"
      severity: "critical"
      channels: ["email", "siem", "pagerduty"]
      
    - name: "mfa_disabled"
      severity: "high"
      channels: ["email", "siem"]
      
    - name: "inactive_user"
      severity: "medium"
      channels: ["email"]

# Security (HIPAA-required)
security:
  # Encryption
  encryption:
    enabled: true
    tls_min_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
  
  # Access controls
  ip_whitelist:
    enabled: true
    allowed_ips:
      - "10.0.0.0/8"  # Internal network only
    block_by_default: true
  
  vpn_required: true
  mfa_required: true
  
  # Session management
  session:
    timeout_minutes: 15
    require_reauth: true
    
  # Audit trail
  audit:
    enabled: true
    log_all_access: true
    log_all_changes: true
    tamper_protection: true

# Compliance (HIPAA)
compliance:
  enabled: true
  
  frameworks:
    hipaa:
      enabled: true
      privacy_rule: true
      security_rule: true
      breach_notification_rule: true
      
      # Technical safeguards
      technical_safeguards:
        access_control: true
        audit_controls: true
        integrity_controls: true
        transmission_security: true
      
      # Administrative safeguards
      administrative_safeguards:
        security_management: true
        workforce_security: true
        information_access_management: true
        security_awareness_training: true
        
      # Physical safeguards
      physical_safeguards:
        facility_access_controls: true
        workstation_security: true
        device_media_controls: true

# Workflows
workflows:
  # PHI detection workflow
  phi_detection:
    enabled: true
    confidence_threshold: 0.6
    immediate_alert: true
    notify_privacy_officer: true
    create_incident: true
    
  # Breach notification workflow
  breach_notification:
    enabled: true
    notification_deadline_hours: 72  # HIPAA requirement
    notify_hhs: true
    notify_affected_individuals: true
    notify_media: false  # Only if >500 individuals
    
  # Access review workflow
  access_review:
    enabled: true
    frequency_days: 90
    require_approval: true
    revoke_unused_access: true

# Scheduled Scans
schedules:
  # Multiple daily scans for HIPAA
  morning_scan:
    enabled: true
    cron: "0 6 * * *"
    command: "scan files --check-phi --full-scan"
    
  afternoon_scan:
    enabled: true
    cron: "0 14 * * *"
    command: "scan files --check-phi --incremental"
    
  evening_scan:
    enabled: true
    cron: "0 22 * * *"
    command: "scan files --check-phi --incremental"
  
  # User access review
  weekly_access_review:
    enabled: true
    cron: "0 8 * * 1"
    command: "scan users --check-mfa --check-inactive"
  
  # Compliance report
  monthly_compliance:
    enabled: true
    cron: "0 9 1 * *"
    command: "report generate --format pdf --type hipaa-compliance"

---

# HIPAA Compliance Checklist

# Technical Safeguards:
# [x] Access Control - MFA, VPN, IP whitelist
# [x] Audit Controls - Comprehensive logging
# [x] Integrity Controls - Encryption, checksums
# [x] Transmission Security - TLS 1.3

# Administrative Safeguards:
# [x] Security Management Process
# [x] Workforce Security
# [x] Information Access Management
# [x] Security Awareness Training

# Physical Safeguards:
# [x] Facility Access Controls
# [x] Workstation Security
# [x] Device and Media Controls

# Documentation:
# [x] Policies and Procedures
# [x] Risk Assessment
# [x] Breach Notification Plan
# [x] Business Associate Agreements

---

# Estimated Costs

# For 500 users, 100,000 files:
# - API calls: ~100,000/day
# - Storage: 10 GB (7-year retention)
# - Compute: 4 cores, 8 GB RAM
# - Network: Moderate

---

# Support Contacts

# Privacy Officer: privacy@healthcare.org
# Security Team: security@healthcare.org
# Compliance Team: compliance@healthcare.org
# IT Support: support@healthcare.org

